"""Add location and indexes to produce

Revision ID: 102e7c8c6658
Revises: b4f87152f709
Create Date: 2025-10-18 19:16:02.119155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102e7c8c6658'
down_revision = 'b4f87152f709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produce', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_produce_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_produce_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produce', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produce_name'))
        batch_op.drop_index(batch_op.f('ix_produce_location'))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
