"""Add indexes for performance optimization

Revision ID: 8a4b23728a65
Revises: 009f0bafacdb
Create Date: 2025-10-18 14:22:45.369173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4b23728a65'
down_revision = '009f0bafacdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_buyer_id'), ['buyer_id'], unique=False)

    with op.batch_alter_table('produce', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produce_farmer_id'), ['farmer_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transactions_checkout_request_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_transactions_checkout_request_id'), ['checkout_request_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_phone_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_phone_number_key'), ['phone_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_checkout_request_id'))
        batch_op.create_unique_constraint(batch_op.f('transactions_checkout_request_id_key'), ['checkout_request_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('produce', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produce_farmer_id'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_buyer_id'))

    # ### end Alembic commands ###
